name: llm-watermark
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=11.8
  - conda-forge::transformers=4.51.3
  - huggingface::datasets=3.6.0
  - conda-forge::tqdm=4.67.1
  - conda-forge::numpy=2.2.5
  - conda-forge::sentencepiece=0.2.0
  - pip
  - pip:
    - accelerate
    - huggingface_hub
